### ISSUE TITLE
tcpkali: unrecognized option `--latency-marker-skip'

### ISSUE THREAD

**Issue by narqo** [machinezone/tcpkali#16]
Looks like the latest version of tcpkali lacks some options described in README.

~~~
  › tcpkali --version
tcpkali version 0.6 (libev)

  › tcpkali -r 50 -c 4 --latency-marker '[1,0,' --latency-marker-skip 2 ···
tcpkali: unrecognized option `--latency-marker-skip'
--latency-marker-skip: unknown option
···
~~~

**Comment by vlm** [comment]
Works for me. Where did you obtain the `tcpkali` binary?

**Comment by narqo** [comment]
I use version from Homebrew (Mac).

**Comment by vlm** [comment]
The `master` branch you are seeing on this github is based on 0.6, but contains additional features. I only tag the repository with a new version when I am about to release a new one. Otherwise, each commit would have to generate a new version number.

I suggest you to build tcpkali from sources to obtain this functionality. Or just wait a few days since I'll push a new version soon.
