### ISSUE TITLE
About latencies and Latency at percentiles

### ISSUE THREAD

**Issue by nsdont** [machinezone/tcpkali#4]
My test report:
```
Destination: [127.0.0.1]:8001
Ramped up to 10 connections.
Total data sent:     0.6 MiB (649285 bytes)
Total data received: 2.4 MiB (2534118 bytes)
Bandwidth per channel: 0.255⇅ Mbps (31.8 kBps)
Aggregate bandwidth: 2.027↓, 0.519↑ Mbps
Latency at percentiles: 616.3/2486.3/2502.3 (95/99/99.5%)
Mean and max latencies: 322.3/2540.7 (mean/max)
Test duration: 10.0029 s.
```

what mean of latencies or Latency at percentiles?

**Comment by vlm** [comment]
There are infinitely many ways to measure latency.
 * One way is to compute an average of all latencies. The problem is that it'll show a weird output which is very dependent on the random latency outliers.
 * Another way is to report the max latency. It will also jump around, since max depends on network conditions, GC pauses, etc.
 * One of the most useful ways to measure latency is to figure out the answer to question "What latency the 95% of requests are finishing with", allowing for small number of outliers.

Read:
 * http://en.wikipedia.org/wiki/Percentile
 * http://www.quora.com/What-is-p99-latency
 * https://engineering.linkedin.com/performance/who-moved-my-99th-percentile-latency
 * https://www.elastic.co/blog/averages-can-dangerous-use-percentile
