### ISSUE TITLE
Latency/tput with tcpkali ? 

### ISSUE THREAD

**Issue by vschiavoni** [machinezone/tcpkali#40]
Hello,
we're trying to measure how many requests per second a given tcpkali can handle before the response time grows to unacceptable values (let's say more than 2/3 seconds).
Ideally, we would like to send as much traffic at fixed rates (either in terms of messages per second or fixed mbit rate) and observe the response latencies. 
Is tcpkali the right tool for this task ? 

What we tried is the following. On the server-side:
`./tcpkali --listen-port 8888 --listen-mode=active -T3h --write-combine=off -m "PONG"`
(we assume the 'PONG' messages are used to reply upon each client request...if this is not the case, how do we enforce it?)

Next, on the client-side:
`/tcpkali  server-node:8888 -m "PING" --latency-marker "PONG" --write-combine=off`

But it seems not to do what we want: the server is sending 'PONG' messages as fast as possible. 

Are doing something conceptually wrong ? 
We are using the master branch from this repository, latest release.

**Comment by vschiavoni** [comment]
I've also tried using a third-party server-node (socat) instead of the tcpkali in server-mode:
`/tcpkali/src# socat TCP-LISTEN:8888,crlf,fork,reuseaddr SYSTEM:"echo PONG"`

The socat output reports a 'broken pipe', as if the client does not wait for the server reply:
`2017/02/28 14:48:51 socat[6406] E write(3, 0xb3d610, 8192): Broken pipe`

**Comment by vlm** [comment]
The client behavior of tcpkali is as you'd expect, so this is correct:

```
tcpkali server-node:8888 -m "PING" --latency-marker "PONG" --write-combine=off
```

However, the server behavior (when tcpkali acts as a server) is somewhat off. Tcpkali is a L4 tool with some provision for websockets. As such, it can't reply to the messages, it can only generate some traffic (or not generate) with a pre-defined rate.

If you want to see the maximum message rate, please use some reflector., such as socat or whatnot. The problem with your reflector is that it is not a streaming reflector (i.e., it closes connection after replying). You need something streaming, such as apache or nginx in HTTP keep-alive mode, or websocket echo responder, or your actual application.

tcpkali alone is not sufficient to check request/response latency. It can be used to estimate the bandwidth though, because it doesn't care about messages and replying to them and just sends stuff as fast as possible.

**Comment by linup2011** [comment]
Hi Lev,

I'm also trying to test latency with tcpkali and nginx. but I don't know how to set nginx and how to use tcpkali. maybe I should set nginx to reply a fixed size file?

could you help to give any guidance? thanks @vlm
